### ISSUE TITLE
Auto Moderacion

### ISSUE THREAD

**Issue by BendyTheTimeTraveler** [Philip-j-fry/Robot-Hamster#2]
I would like to controll Auto Moderacion in Robot Hamster becouse of this
![obraz](https://user-images.githubusercontent.com/32232153/30778732-94676140-a0dd-11e7-9683-767b0e4ceba0.png)

**Comment by Katrixerse** [comment]
@BendyTheTimeTraveler, i have disabled auto mod for now ill work on a new feature like the prefix to be able to turn it on or off 

thanks for the suggestion

**Comment by BendyTheTimeTraveler** [comment]
@Philip-j-fry Your welcome

**Comment by Katrixerse** [comment]
Ill be fixing this today hopefully, auto moderation will be disabled by default and there will be a new command h!automod enable/disable.

**Comment by Katrixerse** [comment]
Made it so auto mod can be enabled/disabled per guild, this was done awhile ago but forgot to put it here
